# Generated by Django 5.2.1 on 2025-05-29 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Comentario')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Comentario del Foro',
                'verbose_name_plural': 'Comentarios del Foro',
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Tema')),
                ('content', models.TextField(verbose_name='Descripción del Tema')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Tema del Foro',
                'verbose_name_plural': 'Temas del Foro',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foro.topic', verbose_name='Tema'),
        ),
    ]
